routes/web.php
<?php

use App\Http\Controllers\NasabahController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TransaksiController;
use App\Models\Nasabah;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return redirect(route('nasabah.index'));
});

Route::resource('users', PostController::class);

Route::controller(NasabahController::class)->group(function(){
    Route::get('/nasabah','index')->name('nasabah.index');
    Route::post('/nasabah/store','store')->name('nasabah.store');

    Route::get('/nasabah/points', 'seePoints')->name('nasabah.points');
    
    Route::get('/nasabah/prints', 'nasabahPrint')->name('nasabah.prints');
    Route::post('/nasabah/prints', 'nasabahPrint')->name('nasabah.prints');
});

// Route::resource('nasabah',NasabahController::class)->except('show');
Route::resource('transaksi',TransaksiController::class)->except('show');

resources/views/create_nasabah.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    table,
    td,
    th {
        border: 1px solid #000;
        padding: 8px;
    }

    table {
        margin-top: 3rem;
        width: 200px;
        border-collapse: collapse;
    }
</style>

<body>
    <h3>Create Nasabah</h3>
    <a href="{{ route('transaksi.index') }}" style="margin-top: 18px;">Tambah data transaksi</a>
    <a href="{{ route('nasabah.points') }}" style="margin-top: 18px;">Lihat poin transaksi</a>
    <a href="{{ route('nasabah.prints') }}" style="margin-top: 18px;">Cetak transaksi</a>
    
    <form action="{{ route('nasabah.store') }}" method="post">
        @csrf
        <label for="customername">Customer Name</label>
        <input type="text" name="customername" id="customername">
        <button type="submit">Save</button>
    </form>
    <table>
        <thead>
            <tr>
                <th>AccountId</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($nasabah as $data)
                <tr>
                    <td>{{ $data->accountId }}</td>
                    <td>{{ $data->name }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">Data kosong</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>

</html>

resources/views/create_transaksi.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    table,
    td,
    th {
        border: 1px solid #000;
        padding: 8px;
    }

    table {
        margin-top: 3rem;
        width: max-content;
        border-collapse: collapse;
    }

    .form-group {
        width: 164px;
        max-width: 280px;
        display: flex;
        flex-flow: column nowrap;
        margin-top: 16px;
    }

    .form-group-option label {
        display: block;
        margin-top: 16px;
    }

    .form-group-option {
        display: inline;
    }

    button {
        margin: 8px 0;
    }
</style>

<body>
    <h3>Create Transaction</h3>
    <a href="{{ route('nasabah.index') }}" style="margin-top: 18px;">Tambah data nasabah</a>
    <a href="{{ route('nasabah.points') }}" style="margin-top: 18px;">Lihat poin transaksi</a>
    <a href="{{ route('nasabah.prints') }}" style="margin-top: 18px;">Cetak transaksi</a>
    
    <form action="{{ route('transaksi.store') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="customerid">Customer ID</label>
            <span>
                Available id 
                @foreach ($listNasabah as $data)
                   {{ $data['accountId'] }},
                @endforeach
            </span>
            <input type="number" min="1" name="customerid" id="customerid">
        </div>
        <div class="form-group">
            <label for="transactdate">Transaction date</label>
            <input type="date" name="transactdate" id="transactdate">
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="description" id="description">
        </div>
        <div class="form-group-option">
            <label for="payment_option">Debit or credit</label>
            <input type="radio" name="payment_option" id="payment_option" value="D">Debit
            <input type="radio" name="payment_option" id="payment_option" value="C">Credit
        </div>
        <div class="form-group">
            <label for="money_amount">Money amount</label>
            <input type="number" min="0" name="money_amount" id="money_amount">
        </div>

        <button type="submit">Save</button>
    </form>
    
    <table>
        <thead>
            <tr>
                <th>AccountId</th>
                <th>Transaction Date</th>
                <th>Description</th>
                <th>Debit or Credit</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($transaksi as $data)
                <tr>
                    <td>{{ $data->account_id }}</td>
                    <td>{{ $data->transaction_date }}</td>
                    <td>{{ $data->description }}</td>
                    <td>{{ $data->debit_credit_status }}</td>
                    <td>{{ number_format($data->amount, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>

resources/views/nasabah_points.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    table,
    td,
    th {
        border: 1px solid #000;
        padding: 8px;
    }

    table {
        margin-top: 3rem;
        width: 200px;
        border-collapse: collapse;
    }
</style>

<body>
    <a href="{{ route('transaksi.index') }}" style="margin-top: 18px;">Tambah data transaksi</a>
    
    <table>
        <thead>
            <tr>
                <th>AccountId</th>
                <th>Name</th>
                <th>Total Point</th>
            </tr>
        </thead>
        <tbody>
            
            @forelse ($listNasabah as $data)
                <tr>
                    <td>{{ $data->accountId }}</td>
                    <td>{{ $data->name }}</td>
                    <td>point</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">Data kosong</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>

</html>

resources/views/nasabah_prints.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<style>
    table,
    td,
    th {
        border: 1px solid #000;
        padding: 8px;
    }

    table {
        margin-top: 3rem;
        width: max-content;
        border-collapse: collapse;
    }

    .form-group {
        width: 164px;
        max-width: 280px;
        display: flex;
        flex-flow: column nowrap;
        margin-top: 16px;
    }

    .form-group-option label {
        display: block;
        margin-top: 16px;
    }

    .form-group-option {
        display: inline;
    }

    button {
        margin: 8px 0;
    }
</style>

<body>
    <h3>Filter Transaction</h3>
    <a href="{{ route('nasabah.index') }}" style="margin-top: 18px;">Tambah data nasabah</a>
    <a href="{{ route('nasabah.points') }}" style="margin-top: 18px;">Lihat poin transaksi</a>
    
    <form action="" method="get">
        {{-- @csrf --}}
        <div class="form-group">
            <label for="customerid">Customer ID</label>
            <span>
                Available id @foreach ($listNasabah as $data)
                    {{ $data['accountId'] }},
                @endforeach
            </span>
            <input type="number" min="1" name="customerid" id="customerid">
        </div>
        <div class="form-group">
            <label for="start_date">Start date</label>
            <input type="date" name="start_date" id="start_date">
        </div>
        <div class="form-group">
            <label for="end_date">End date</label>
            <input type="date" name="end_date" id="end_date">
        </div>
        <button type="submit">Filter</button>
    </form>
    @if (request()->has('customerid'))
        <p>CustomerID <strong>{{ request()->get('customerid') }}</strong> | Start date : {{ request()->get('start_date') }}, End date : {{ request()->get('end_date') }}</p>
    @endif
    <table>
        <thead>
            <tr>
                <th>Transaction Date</th>
                <th>Description</th>
                <th>Credit</th>
                <th>Debit</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @if (empty($transaksi))
                <tr>
                    <td colspan="5">Tidak ada data</td>
                </tr>
            @else
                @foreach ($transaksi as $data)
                    <tr>
                        <td>{{ $data->transaction_date }}</td>
                        <td>{{ $data->description }}</td>
                        <td>
                            @if ($data->debit_credit_status === 'C')
                                {{ number_format($data->amount, 0, ',', '.') }}
                            @else
                                -
                            @endif
                        </td>
                        <td>
                            @if ($data->debit_credit_status === 'D')
                                {{ number_format($data->amount, 0, ',', '.') }}
                            @else
                                -
                            @endif
                        </td>
                        <td>{{ number_format($data->amount, 0, ',', '.') }}</td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
</body>

</html>